apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: auth
  template:
    metadata:
      labels:
        component: auth
    spec:
      containers:
        - name: auth
          image: josefvivas/demo-auth
          ports:
            - containerPort: 4001
          env:
            - name: SECRET_JWT
              valueFrom:
                secretKeyRef:
                  name: demo-secret
                  key: SECRET_JWT
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: demo-secret
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: demo-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: demo-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: demo-secret
                  key: DB_NAME
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: demo-secret
                  key: DB_PORT
